global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scheme: https
    static_configs:
      - targets: ['localhost:9090']
    tls_config:
      ca_file: /etc/prometheus/certs/ca.crt
      insecure_skip_verify: false

  - job_name: 'nginx-exporter'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['exporter-proxy:9113']
    tls_config:
      ca_file: /etc/prometheus/certs/ca.crt
      insecure_skip_verify: false
